### ISSUE TITLE
can't require in node environment

### ISSUE THREAD

**Issue by inyono** [ory/editor#300]
When requiring `ory-editor` in node, we get the following error:
```
Error: secure random number generation not supported by this browser
use chrome, FireFox or Internet Explorer 11
    at oldBrowser (/Users/inyono/Projects/creator-electron/node_modules/ory-editor/dist/bundle.js:19962:9)
    at _rng (/Users/inyono/Projects/creator-electron/node_modules/ory-editor/dist/bundle.js:42874:53)
    at /Users/inyono/Projects/creator-electron/node_modules/ory-editor/dist/bundle.js:42935:20
    at Object.<anonymous> (/Users/inyono/Projects/creator-electron/node_modules/ory-editor/dist/bundle.js:43086:3)
    at Object.<anonymous> (/Users/inyono/Projects/creator-electron/node_modules/ory-editor/dist/bundle.js:43088:30)
    at __webpack_require__ (/Users/inyono/Projects/creator-electron/node_modules/ory-editor/dist/bundle.js:30:30)
    at Object.defineProperty.value (/Users/inyono/Projects/creator-electron/node_modules/ory-editor/dist/bundle.js:66244:17)
    at __webpack_require__ (/Users/inyono/Projects/creator-electron/node_modules/ory-editor/dist/bundle.js:30:30)
    at Object.defineProperty.value (/Users/inyono/Projects/creator-electron/node_modules/ory-editor/dist/bundle.js:18584:16)
    at __webpack_require__ (/Users/inyono/Projects/creator-electron/node_modules/ory-editor/dist/bundle.js:30:30)
```
Probably related to https://github.com/ory-am/editor/blob/3b45de08e602b75fae93f968d5f451f0f150c422/src/editor/index.js#L15

We should at least be able to use `editor.renderToHtml` without throwing errors.

**Comment by arekkas** [comment]
Weird, this worked in the local node environment. By the way, the breaking flag is for flagging breaking changes :)

**Comment by arekkas** [comment]
This should be resolved
