### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by daneb** [ory/editor#411]
Hi guys

Ran into this issue on 0.3.2 and 0.3.6 when I re-open a closed project after quitting the application and saving.

```
Uncaught Exception:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Applications/ORY Sites.app/Contents/Resources/app.asar/transpiled/shared/services/project/pages.js:55:94
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
```

*To re-produce:*
1. New Project: Open application -> New Project -> x.com -> New Location (Browse) -> New Folder -> Specify Folder Name (x.com) -> url http://x.com.
2.  Modify: Change Title
3. Save
4. Export 
5. Close Application
6. Open Application -> Click on x.com on Recent Project list.

Currently running: MacOs 10.12.4 Sierra

Thanks
Dane

**Comment by arekkas** [comment]
Hey thank you for the report, I'll investigate this today!

**Comment by arekkas** [comment]
I wasn't able to reproduce this on windows, I will check it later on my macbook!

**Comment by daneb** [comment]
Thanks for the feedback.
The impact is quite high in the sense that I can’t make a project, close it and come back to it. It’s pretty much rendered useless.

HOWEVER there is absolutely no rush ;)

Dane

www.danebalia.com
www.codedtrue.com

**Comment by arekkas** [comment]
I can't reproduce this on my macbook either. @daneb, would you mind uploading the `x.com.osp` file in the project root to [http://gist.github.com/](http://gist.github.com/)?

**Comment by daneb** [comment]
Hi Aeneas

Here you go:
https://gist.github.com/daneb/5f25d40a90d7b7251ff03545329666c7

And here is the entire project in case (compressed zip):
https://www.dropbox.com/s/aozqnp45mwjtdd6/danebalia.com.zip?dl=0


Dane

www.danebalia.com
www.codedtrue.com

**Comment by arekkas** [comment]
Ok that's weird, seems like the page file is empty (`pages/8596e49f-b6dc-4e66-9261-dee6b0bf5df3.json`), but the back ups are fine (`pages/8596e49f-b6dc-4e66-9261-dee6b0bf5df3.json.34a9e885-d7d6-4163-a0e7-aac730ba23fe.bak`). Could you try creating a new project and see if the error occurrs again?

**Comment by arekkas** [comment]
Also, could you share the output of `cat ~/Library/Logs/ORY\ Sites/log.log` with me?

**Comment by daneb** [comment]
Hi again

Apologies for delay.

[2017-05-28 21:05:03:0766] [info] Application main process ready
[2017-05-28 21:05:39:0875] [info] Application main process ready
[2017-05-28 21:05:39:0879] [info] Initializing application
[2017-05-28 21:05:40:0002] [info] No token was found, triggering authentication screen
[2017-05-28 21:05:40:0122] [info] Checking for update
[2017-05-28 21:05:42:0451] [info] Update for version 0.3.2 is not available (latest version: 0.3.2, downgrade is disallowed.
[2017-05-28 21:05:43:0474] [info] Setting up raven...
[2017-05-28 21:05:43:0481] [info] Setting up raven in the browser
[2017-05-28 21:05:45:0667] [info] Authentication window caught redirect request { now: 'https://cloud.ory.am/oauth2/auth?scope=offline%20openid%20ory.sites%20force-consent%20profile%20email&state=709a7a64-5c29-4298-bc74-aac24deedaf5&nonce=646268ab-82ee-4d27-b95a-8f9d10cc0efd&redirectURI=https%3A%2F%2Fsites-app%2Fcallback&response_type=code&client_id=ory.cloud-platform.sites-app',
  next: 'https://cloud.ory.am/consent?challenge=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJvcnkuY2xvdWQtcGxhdGZvcm0uc2l0ZXMtYXBwIiwiZXhwIjoxNDk1OTk4OTQ1LCJqdGkiOiIzYTRmN2UxMS0zOWM0LTQ3NzktYTFlMC1lMzc5Yjg3NDNjOWUiLCJyZWRpciI6Imh0dHA6Ly9jbG91ZC5vcnkuYW0vb2F1dGgyL2F1dGg_Y2xpZW50X2lkPW9yeSUyZWNsb3VkJTJkcGxhdGZvcm0lMmVzaXRlcyUyZGFwcFx1MDAyNm5vbmNlPTY0NjI2OGFiJTJkODJlZSUyZDRkMjclMmRiOTVhJTJkOGY5ZDEwY2MwZWZkXHUwMDI2cmVkaXJlY3RVUkk9aHR0cHMlM2ElMmYlMmZzaXRlcyUyZGFwcCUyZmNhbGxiYWNrXHUwMDI2cmVzcG9uc2VfdHlwZT1jb2RlXHUwMDI2c2NvcGU9b2ZmbGluZSUyMG9wZW5pZCUyMG9yeSUyZXNpdGVzJTIwZm9yY2UlMmRjb25zZW50JTIwcHJvZmlsZSUyMGVtYWlsXHUwMDI2c3RhdGU9NzA5YTdhNjQlMmQ1YzI5JTJkNDI5OCUyZGJjNzQlMmRhYWMyNGRlZWRhZjUiLCJzY3AiOlsib2ZmbGluZSIsIm9wZW5pZCIsIm9yeS5zaXRlcyIsImZvcmNlLWNvbnNlbnQiLCJwcm9maWxlIiwiZW1haWwiXX0.HyTczC2cgXiRuyV8uLqwVP_i5mSvXOKVT1piwMqMi-m5Rel-dQcQI8WAxXmF_cQInvE5JXflkIss4dGzbZI82sLxusJEgIVnA7x-BkhlmMt2aRbF0KbVbRX8Uc0wo7rr0eIo1GpIZihblEqr39KRrI8D2BABowOKRxyS0pk_7J6_yiVmsXIH4PogJoQTCRcfDyDB5NXY5nN6r8YB26h4ml95wSDHxp1YaJ3HQvXbRujRBlYOaFAMuH25EKaEuufjFiZN5ZyGaEV2g-uCRB9DQVOhwcNY7NhgJJn6Ss4n8uXN6536g_Cq9uX1QGwcOX_Y2NFQyogpRB6qkpRX6X2POV-qPvd4sX0JSm50fepDx057LnDAgkFgg_FnSyYnfE7LijQbOonHXxg5MC65q0b_K8QqmGqzHnT1rrjkAeRbCft1JfgsUoQQP5DMDOUASi3P-tBL015KfsoV6adnJ8HY1FVsIzV0AmLlGStavAZZTAN5FivT8eY7ip1Z7HDktrGZ0nY4K_XcOH19Ibh2EsguT1z0m1y_LPkIulbynf8Oy1xB_jTyZojwQQltdoFwug-EvhxNC-KWCu5H_twCnn3-g5T6onopUWXqwMhrRc50sIOFnRsLKMnKsEYJKYmXWW_Dc4wuBsrhUPgPgcwK4MnD4ZEsWB8Wjyh-y8_0BmhRNiI' }
[2017-05-28 21:05:46:0125] [info] Authentication window caught redirect request { now: 'https://cloud.ory.am/consent?challenge=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJvcnkuY2xvdWQtcGxhdGZvcm0uc2l0ZXMtYXBwIiwiZXhwIjoxNDk1OTk4OTQ1LCJqdGkiOiIzYTRmN2UxMS0zOWM0LTQ3NzktYTFlMC1lMzc5Yjg3NDNjOWUiLCJyZWRpciI6Imh0dHA6Ly9jbG91ZC5vcnkuYW0vb2F1dGgyL2F1dGg_Y2xpZW50X2lkPW9yeSUyZWNsb3VkJTJkcGxhdGZvcm0lMmVzaXRlcyUyZGFwcFx1MDAyNm5vbmNlPTY0NjI2OGFiJTJkODJlZSUyZDRkMjclMmRiOTVhJTJkOGY5ZDEwY2MwZWZkXHUwMDI2cmVkaXJlY3RVUkk9aHR0cHMlM2ElMmYlMmZzaXRlcyUyZGFwcCUyZmNhbGxiYWNrXHUwMDI2cmVzcG9uc2VfdHlwZT1jb2RlXHUwMDI2c2NvcGU9b2ZmbGluZSUyMG9wZW5pZCUyMG9yeSUyZXNpdGVzJTIwZm9yY2UlMmRjb25zZW50JTIwcHJvZmlsZSUyMGVtYWlsXHUwMDI2c3RhdGU9NzA5YTdhNjQlMmQ1YzI5JTJkNDI5OCUyZGJjNzQlMmRhYWMyNGRlZWRhZjUiLCJzY3AiOlsib2ZmbGluZSIsIm9wZW5pZCIsIm9yeS5zaXRlcyIsImZvcmNlLWNvbnNlbnQiLCJwcm9maWxlIiwiZW1haWwiXX0.HyTczC2cgXiRuyV8uLqwVP_i5mSvXOKVT1piwMqMi-m5Rel-dQcQI8WAxXmF_cQInvE5JXflkIss4dGzbZI82sLxusJEgIVnA7x-BkhlmMt2aRbF0KbVbRX8Uc0wo7rr0eIo1GpIZihblEqr39KRrI8D2BABowOKRxyS0pk_7J6_yiVmsXIH4PogJoQTCRcfDyDB5NXY5nN6r8YB26h4ml95wSDHxp1YaJ3HQvXbRujRBlYOaFAMuH25EKaEuufjFiZN5ZyGaEV2g-uCRB9DQVOhwcNY7NhgJJn6Ss4n8uXN6536g_Cq9uX1QGwcOX_Y2NFQyogpRB6qkpRX6X2POV-qPvd4sX0JSm50fepDx057LnDAgkFgg_FnSyYnfE7LijQbOonHXxg5MC65q0b_K8QqmGqzHnT1rrjkAeRbCft1JfgsUoQQP5DMDOUASi3P-tBL015KfsoV6adnJ8HY1FVsIzV0AmLlGStavAZZTAN5FivT8eY7ip1Z7HDktrGZ0nY4K_XcOH19Ibh2EsguT1z0m1y_LPkIulbynf8Oy1xB_jTyZojwQQltdoFwug-EvhxNC-KWCu5H_twCnn3-g5T6onopUWXqwMhrRc50sIOFnRsLKMnKsEYJKYmXWW_Dc4wuBsrhUPgPgcwK4MnD4ZEsWB8Wjyh-y8_0BmhRNiI',
  next: 'https://cloud.ory.am/login' }
[2017-05-28 21:05:48:0509] [error] Could not load login frame Uncaught Error: Bootstrap's JavaScript requires jQuery
[2017-05-28 21:07:27:0338] [info] Authentication window caught redirect request { now: 'https://ory.eu.auth0.com/login/callback',
  next: 'https://cloud.ory.am/auth/callback?code=1vTy8TelwJeqfE14' }
[2017-05-28 21:07:28:0880] [info] Authentication window caught redirect request { now: 'https://cloud.ory.am/auth/callback?code=1vTy8TelwJeqfE14',
  next: 'https://cloud.ory.am/consent?challenge=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9%2eeyJhdWQiOiJvcnkuY2xvdWQtcGxhdGZvcm0uc2l0ZXMtYXBwIiwiZXhwIjoxNDk1OTk4OTQ1LCJqdGkiOiIzYTRmN2UxMS0zOWM0LTQ3NzktYTFlMC1lMzc5Yjg3NDNjOWUiLCJyZWRpciI6Imh0dHA6Ly9jbG91ZC5vcnkuYW0vb2F1dGgyL2F1dGg_Y2xpZW50X2lkPW9yeSUyZWNsb3VkJTJkcGxhdGZvcm0lMmVzaXRlcyUyZGFwcFx1MDAyNm5vbmNlPTY0NjI2OGFiJTJkODJlZSUyZDRkMjclMmRiOTVhJTJkOGY5ZDEwY2MwZWZkXHUwMDI2cmVkaXJlY3RVUkk9aHR0cHMlM2ElMmYlMmZzaXRlcyUyZGFwcCUyZmNhbGxiYWNrXHUwMDI2cmVzcG9uc2VfdHlwZT1jb2RlXHUwMDI2c2NvcGU9b2ZmbGluZSUyMG9wZW5pZCUyMG9yeSUyZXNpdGVzJTIwZm9yY2UlMmRjb25zZW50JTIwcHJvZmlsZSUyMGVtYWlsXHUwMDI2c3RhdGU9NzA5YTdhNjQlMmQ1YzI5JTJkNDI5OCUyZGJjNzQlMmRhYWMyNGRlZWRhZjUiLCJzY3AiOlsib2ZmbGluZSIsIm9wZW5pZCIsIm9yeS5zaXRlcyIsImZvcmNlLWNvbnNlbnQiLCJwcm9maWxlIiwiZW1haWwiXX0%2eHyTczC2cgXiRuyV8uLqwVP_i5mSvXOKVT1piwMqMi%2dm5Rel%2ddQcQI8WAxXmF_cQInvE5JXflkIss4dGzbZI82sLxusJEgIVnA7x%2dBkhlmMt2aRbF0KbVbRX8Uc0wo7rr0eIo1GpIZihblEqr39KRrI8D2BABowOKRxyS0pk_7J6_yiVmsXIH4PogJoQTCRcfDyDB5NXY5nN6r8YB26h4ml95wSDHxp1YaJ3HQvXbRujRBlYOaFAMuH25EKaEuufjFiZN5ZyGaEV2g%2duCRB9DQVOhwcNY7NhgJJn6Ss4n8uXN6536g_Cq9uX1QGwcOX_Y2NFQyogpRB6qkpRX6X2POV%2dqPvd4sX0JSm50fepDx057LnDAgkFgg_FnSyYnfE7LijQbOonHXxg5MC65q0b_K8QqmGqzHnT1rrjkAeRbCft1JfgsUoQQP5DMDOUASi3P%2dtBL015KfsoV6adnJ8HY1FVsIzV0AmLlGStavAZZTAN5FivT8eY7ip1Z7HDktrGZ0nY4K_XcOH19Ibh2EsguT1z0m1y_LPkIulbynf8Oy1xB_jTyZojwQQltdoFwug%2dEvhxNC%2dKWCu5H_twCnn3%2dg5T6onopUWXqwMhrRc50sIOFnRsLKMnKsEYJKYmXWW_Dc4wuBsrhUPgPgcwK4MnD4ZEsWB8Wjyh%2dy8_0BmhRNiI' }

Dane

www.danebalia.com
www.codedtrue.com

**Comment by arekkas** [comment]
Sorry, for some reason the notification was marked as spam. Where you able to create a new project and test if that works?

**Comment by daneb** [comment]
Hi @arekkas 

I created a new project and it worked. Which made me question what about the other ones I created didn't. Unfortunately I have been unable to replicate it.

If it happens again will post here.

Thanks

**Comment by deftsoftlive** [comment]
uyh
