### ISSUE TITLE
Project won't open - TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by hemantasapkota** [ory/editor#451]
Hi,

My project has stopped rendering. I haven't made any changes to files. 

Environment: MacOSX Sierra

The following is displayed on the editor:

```
TypeError: Cannot read property 'id' of undefined
    at renderEditor (/Applications/ORY Sites.app/Contents/Resources/app.asar/transpiled/server/index.js:121:205)
    at Layer.handle [as handle_request] (/Applications/ORY Sites.app/Contents/Resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Applications/ORY Sites.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:317:13)
    at /Applications/ORY Sites.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Applications/ORY Sites.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:335:12)
    at next (/Applications/ORY Sites.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/Applications/ORY Sites.app/Contents/Resources/app.asar/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:96:13)
    at SendStream.emit (events.js:188:7)
    at SendStream.error (/Applications/ORY Sites.app/Contents/Resources/app.asar/node_modules/send/index.js:282:17)
    at SendStream.onStatError (/Applications/ORY Sites.app/Contents/Resources/app.asar/node_modules/send/index.js:433:12)
    at next (/Applications/ORY Sites.app/Contents/Resources/app.asar/node_modules/send/index.js:771:28)
    at /Applications/ORY Sites.app/Contents/Resources/app.asar/node_modules/send/index.js:779:23
    at FSReqWrap.oncomplete (fs.js:112:15)
```

Thanks

**Comment by arekkas** [comment]
Could you share the project files with me?
